# Change these first
owner: andikarekatias # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: andikarekatias

sites:
  - name: Andika Rekatias
    url: https://andikarekatias.com
  - name: Mediakepri
    url: https://mediakepri.co.id
    headers:
      - "User-Agent: <name> uptime"
  - name: Beritabatam
    url: https://beritabatam.com
  - name: Meutiaranews
    url: https://meutiaranews.co
  - name: Lendoot
    url: https://lendoot.com
  - name: SMK Real Informatika
    url: https://smkrealinformatika.sch.id

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.andikarekatias.com
  # baseUrl: /your-repo-name
  logoUrl: https://andikarekatias.com/assets/img/ar-logo-bw-x54.png
  favicon: https://andikarekatias.com/assets/img/favicon.ico
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status page for all the sites I personally manage.
  navbar:
    - title: Status
      href: /
    - title: Andika Rekatias
      href: https://andikarekatias.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
